Require libticalcs2>=0.1.0 because of ticalcs_calc_send_flash2->ticalcs_calc_send_app2 API change.
git-svn-id: http://svn.tilp.info/repos/tiemu@2092 4f589446-7ac1-0310-82c7-a055b08196ef

diff --git a/tiemu/trunk/configure b/tiemu/trunk/configure
--- a/tiemu/trunk/configure
+++ b/tiemu/trunk/configure
@@ -27481,23 +27481,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for ticalcs2 >= 0.0.1" >&5
-echo $ECHO_N "checking for ticalcs2 >= 0.0.1... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for ticalcs2 >= 0.1.0" >&5
+echo $ECHO_N "checking for ticalcs2 >= 0.1.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "ticalcs2 >= 0.0.1" ; then
+        if $PKG_CONFIG --exists "ticalcs2 >= 0.1.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking TICALCS_CFLAGS" >&5
 echo $ECHO_N "checking TICALCS_CFLAGS... $ECHO_C" >&6
-            TICALCS_CFLAGS=`$PKG_CONFIG --cflags "ticalcs2 >= 0.0.1"`
+            TICALCS_CFLAGS=`$PKG_CONFIG --cflags "ticalcs2 >= 0.1.0"`
             echo "$as_me:$LINENO: result: $TICALCS_CFLAGS" >&5
 echo "${ECHO_T}$TICALCS_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking TICALCS_LIBS" >&5
 echo $ECHO_N "checking TICALCS_LIBS... $ECHO_C" >&6
-            TICALCS_LIBS=`$PKG_CONFIG --libs "ticalcs2 >= 0.0.1"`
+            TICALCS_LIBS=`$PKG_CONFIG --libs "ticalcs2 >= 0.1.0"`
             echo "$as_me:$LINENO: result: $TICALCS_LIBS" >&5
 echo "${ECHO_T}$TICALCS_LIBS" >&6
         else
@@ -27505,7 +27505,7 @@ echo "${ECHO_T}$TICALCS_LIBS" >&6
             TICALCS_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            TICALCS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "ticalcs2 >= 0.0.1"`
+            TICALCS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "ticalcs2 >= 0.1.0"`
             echo $TICALCS_PKG_ERRORS
         fi
 
@@ -27520,8 +27520,8 @@ echo "${ECHO_T}$TICALCS_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (ticalcs2 >= 0.0.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (ticalcs2 >= 0.0.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (ticalcs2 >= 0.1.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (ticalcs2 >= 0.1.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
